function y = bridgeCrane_h(l,s,theta)
%bridgeCrane_h
%    Y = bridgeCrane_h(L,S,THETA)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    28-Nov-2024 16:57:39

y = s+l.*sin(theta);
end
