function y = bridgeCrane_h(l,s,theta)
%bridgeCrane_h
%    Y = bridgeCrane_h(L,S,THETA)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    27-Nov-2024 12:44:55

y = s+l.*sin(theta);
end
