function xd = bridgeCrane_f(Fext,M,g,l,m,sd,sigma,theta,thetad)
%bridgeCrane_f
%    XD = bridgeCrane_f(Fext,M,G,L,m,SD,SIGMA,THETA,THETAD)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    27-Nov-2024 12:44:54

t2 = cos(theta);
t3 = sin(theta);
t4 = l.^2;
t5 = m.^2;
t6 = thetad.^2;
t7 = t2.^2;
t8 = m.*t7;
t9 = -t8;
t10 = M+m+t9;
t11 = 1.0./t10;
xd = [sd;(t11.*(Fext.*l+sigma.*t2.*thetad+m.*t3.*t4.*t6+g.*l.*m.*t2.*t3))./l;thetad;-(t11.*(M.*sigma.*thetad+m.*sigma.*thetad+g.*l.*t3.*t5+Fext.*l.*m.*t2+M.*g.*l.*m.*t3+t2.*t3.*t4.*t5.*t6))./(m.*t4)];
end
