function eigVal = eigVal_A(Fext,M,g,l,m,sigma,theta,thetad)
%eigVal_A
%    eigVal = eigVal_A(Fext,M,G,L,m,SIGMA,THETA,THETAD)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    28-Nov-2024 16:57:40

t2 = cos(theta);
t3 = sin(theta);
t4 = M.*sigma;
t5 = m.*sigma;
t6 = M.^2;
t7 = l.^2;
t8 = l.^3;
t10 = m.^2;
t11 = m.^3;
t14 = thetad.^2;
t9 = t7.^2;
t12 = t10.^2;
t15 = t2.^2;
t16 = t2.^3;
t18 = t3.^2;
t19 = M.*m.*t7;
t20 = t4.^2;
t21 = t4.*t5.*2.0;
t22 = t7.*t10;
t23 = t5.^2;
t24 = Fext.*t3.*t8.*t11.*4.0;
t28 = Fext.*M.*t3.*t8.*t10.*4.0;
t31 = M.*g.*t2.*t8.*t11.*8.0;
t34 = g.*t2.*t6.*t8.*t10.*4.0;
t17 = t15.^2;
t25 = t15.*t22;
t26 = g.*t2.*t8.*t12.*4.0;
t29 = t2.*t3.*t22.*thetad.*2.0;
t32 = g.*t8.*t12.*t16.*4.0;
t33 = -t31;
t35 = M.*g.*t8.*t11.*t16.*4.0;
t36 = t9.*t12.*t14.*t15.*4.0;
t38 = t9.*t12.*t14.*t18.*4.0;
t39 = t15.*t24;
t40 = t2.*t3.*t5.*t22.*thetad.*1.2e+1;
t41 = -t34;
t43 = M.*t9.*t11.*t14.*t15.*4.0;
t44 = M.*t9.*t11.*t14.*t18.*4.0;
t45 = g.*t2.*t8.*t12.*t18.*8.0;
t46 = t2.*t3.*t4.*t22.*thetad.*1.2e+1;
t48 = t18.*t31;
t49 = t9.*t12.*t14.*t15.*t18.*8.0;
t27 = -t26;
t30 = -t25;
t37 = t9.*t12.*t14.*t17.*4.0;
t42 = -t36;
t47 = -t43;
t50 = t19+t22+t30;
t52 = t20+t21+t23+t24+t27+t28+t32+t33+t35+t37+t38+t39+t40+t41+t42+t44+t45+t46+t47+t48+t49;
t51 = 1.0./t50;
t53 = sqrt(t52);
eigVal = [0.0;0.0;t51.*(t4+t5+t29+t53).*(-1.0./2.0);t51.*(t4+t5+t29-t53).*(-1.0./2.0)];
end
