function C = jacobian_C(l,theta)
%jacobian_C
%    C = jacobian_C(L,THETA)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    28-Nov-2024 16:57:40

C = [1.0,0.0,l.*cos(theta),0.0];
end
