function B = jacobian_B(M,l,m,theta)
%jacobian_B
%    B = jacobian_B(M,L,m,THETA)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    28-Nov-2024 16:57:39

t2 = cos(theta);
t3 = t2.^2;
t4 = m.*t3;
t5 = -t4;
t6 = M+m+t5;
t7 = 1.0./t6;
B = [0.0;t7;0.0;-(t2.*t7)./l];
end
