function A = jacobian_A(Fext,M,g,l,m,sigma,theta,thetad)
%jacobian_A
%    A = jacobian_A(Fext,M,G,L,m,SIGMA,THETA,THETAD)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    28-Nov-2024 16:57:39

t2 = cos(theta);
t3 = sin(theta);
t4 = l.^2;
t5 = m.^2;
t6 = thetad.^2;
t9 = 1.0./l;
t11 = 1.0./m;
t7 = t2.^2;
t8 = t3.^2;
t10 = 1.0./t4;
t12 = m.*t7;
t13 = -t12;
t14 = M+m+t13;
t15 = 1.0./t14;
t16 = t15.^2;
A = reshape([0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,t9.*t15.*(g.*l.*t12-sigma.*t3.*thetad-g.*l.*m.*t8+m.*t2.*t4.*t6)-m.*t2.*t3.*t9.*t16.*(Fext.*l+sigma.*t2.*thetad+m.*t3.*t4.*t6+g.*l.*m.*t2.*t3).*2.0,0.0,-t10.*t11.*t15.*(g.*l.*t2.*t5+t4.*t5.*t6.*t7-t4.*t5.*t6.*t8-Fext.*l.*m.*t3+M.*g.*l.*m.*t2)+t2.*t3.*t10.*t16.*(M.*sigma.*thetad+m.*sigma.*thetad+g.*l.*t3.*t5+Fext.*l.*m.*t2+M.*g.*l.*m.*t3+t2.*t3.*t4.*t5.*t6).*2.0,0.0,t9.*t15.*(sigma.*t2+m.*t3.*t4.*thetad.*2.0),1.0,-t10.*t11.*t15.*(M.*sigma+m.*sigma+t2.*t3.*t4.*t5.*thetad.*2.0)],[4,4]);
end
